[versions]
androidGradle = "7.1.0"
kotlin = "1.6.10"
ktlintGradle = "10.2.1"
pluginPublish = "0.19.0"
metalavaGradle = "0.2.1"

[plugins]
ktlintGradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
metalavaGradle = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalavaGradle" }

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
