[versions]
agp = "9.0.0"
kotlin = "2.3.10"
androidx-compose-runtime = "1.10.4"
android-metalava = "1.0.0-alpha14"
jvmTarget = "17"
minGradle = "9.0.0"
compileSdk = "36"
minSdk = "21"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-kmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
metalava = { id = "me.tylerbwong.gradle.metalava" }
pluginPublish = "com.gradle.plugin-publish:2.0.0"
metalavaGradle = "me.tylerbwong.gradle.metalava:0.4.0-alpha03"
buildConfig = "com.github.gmazzo.buildconfig:6.0.7"
spotless = "com.diffplug.spotless:8.2.1"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-gradlePluginApi = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

android-metalava = { module = "com.android.tools.metalava:metalava", version.ref = "android-metalava" }
androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"
# Dummy to get renovate updates, the version is used in rootProject build.gradle with spotless.
ktfmt = "com.facebook:ktfmt:0.61"

junit-bom = "org.junit:junit-bom:6.0.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
