[versions]
androidGradle = "8.7.3"
androidx-compose-runtime = "1.7.5"
junit = "5.11.3"
kotlin = "2.1.0"
ktlintGradle = "12.3.0"
pluginPublish = "1.3.0"
metalavaGradle = "0.4.0-alpha03"

[plugins]
android-lint = { id = "com.android.lint", version.ref = "androidGradle" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlintGradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
metalavaGradle = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalavaGradle" }

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-gradlePluginLints = "androidx.lint:lint-gradle:1.0.0-alpha05"
