[versions]
androidGradle = "8.13.2"
androidx-compose-runtime = "1.10.1"
junit = "5.11.3"
kotlin = "2.3.0"
ktlintGradle = "14.0.1"
pluginPublish = "2.0.0"
metalavaGradle = "0.4.0-alpha03"

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlintGradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
metalavaGradle = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalavaGradle" }

[libraries]
androidGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradle" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
