[versions]
agp = "8.13.2"
kotlin = "2.3.0"
androidx-compose-runtime = "1.10.2"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
metalava = { id = "me.tylerbwong.gradle.metalava" }
ktlintGradle = "org.jlleitschuh.gradle.ktlint:14.0.1"
pluginPublish = "com.gradle.plugin-publish:2.0.0"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

junit-bom = "org.junit:junit-bom:6.0.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiterParams = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
